#!/bin/bash
#
# Usage:
#   ./regtest.sh <function name>

set -o nounset
set -o pipefail
set -o errexit

readonly THIS_DIR=$(dirname $0)
readonly REPO_ROOT=$THIS_DIR
readonly CLIENT_DIR=$REPO_ROOT/client/python

# All the Python tools need this
export PYTHONPATH=$CLIENT_DIR


run-all() {
  mkdir --verbose -p _tmp/regtest
  # Print the spec
  #
  # -n3 has to match the number of arguments in the spec.
  tests/rappor_regtest.py \
    | xargs -n12 -P10 --verbose -- $0 _run-one-case

  # After these are done in parallel
  #
  # Output summary
  # Then cat _tmp/regtest/t*/metrics.csv
}

# Private, don't rely on the arguments
# This is the format generated by the test spec.
_run-one-case() {
  local test_case_id=$1
  local dist=$2
  local num_clients=$3
  local num_unique_values=$4

  local num_bits=$5
  local num_hashes=$6
  local num_cohorts=$7
  local p=$8
  local q=$9
  local f=${10}  # need curly braces to get 10th arg

  local num_additional=${11}
  local to_remove=${12}

  # ...

  echo "ID $test_case_id"
  echo "GOT $@"

  echo "P Q F $p $q $f"

  echo "$num_additional $to_remove"

  #tests/gen_sim_input.py -h || true

  # NOTE: Have to name inputs and outputs by the test case name
  # _tmp/test/t1
  ./demo.sh gen-sim-input-demo $dist $num_clients $num_unique_values
  return

  tests/rappor_sim.py -h || true

  tests/analyze.R -h || true
  echo $?

  # reads input from params dir
  tests/analyze.R _tmp/$test_case_id _tmp/$test_case_id
}

"$@"
